name: "Terraform"

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
    defaults:
      run:
        working-directory: Infra-terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: v1.12.2
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: |
          if terraform apply -auto-approve; then
            echo "Apply succeeded"
          else
            echo "Apply failed, attempting to import existing resources"
            terraform import aws_iam_role.glue_role reddit_glue_role || true
            terraform import aws_s3_bucket.my_bucket reddit-pipeline1234 || true
            terraform import aws_glue_catalog_database.reddit_db reddit_db || true
            terraform apply -auto-approve
          fi